# Generated by Django 5.1.6 on 2025-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('games', models.ManyToManyField(related_name='wishlists', to='gamesdb.game')),
            ],
        ),
    ]
