# Generated by Django 5.1.6 on 2025-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
