# Generated by Django 5.1.6 on 2025-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='gamesdb.game'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='userid',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
